topics:
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : insanity
  topic   : /insanity/cmd_vel
  timeout : 0.5
  priority: 3
- name    : autonomy
  topic   : /move_base/cmd_vel
  timeout : 0.5
  priority: 2
# - name    : autonomy
  # topic   : /kymco_maxxer90_ackermann_steering_controller/cmd_vel
  # timeout : 0.5
  # priority: 2
- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 1

locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255
