# http://official-rtab-map-forum.67519.x6.nabble.com/Problem-with-global-and-local-costmap-td1867.html

footprint: [ [0.65, -0.425], [-1.0, -0.425], [-1.0, 0.425], [0.65, 0.425] ]
transform_tolerance: 0.7

obstacle_layer:
    max_obstacle_height: 1.0 # should be a little higher than the robot's height
    obstacle_range: 4.5
    raytrace_range: 5.0     # check parameter "Grid/RangeMax" at rtabmap_mapping.launch
    footprint_clearing_enabled: true

    observation_sources: point_cloud2_sensor #scan_sensor point_cloud2_sensor
    #scan_sensor: {
    #    data_type: LaserScan,
    #    topic: /scan_obstacles,
    #    clearing: true,
    #    marking: true,
    #    sensor_frame: rgbd_optical_camera_frame,
    #    observation_persistence: 0.0,
    #    expected_update_rate: 0.0,
    #    inf_is_valid: true
    #}

    point_cloud2_sensor: {
        data_type: PointCloud2,
        topic: /octomap_obstacles, #/planner_cloud, #/octomap_obstacles,
        clearing: true,
        marking: true,
        sensor_frame: rgbd_optical_camera_frame,
        observation_persistence: 0.0,
        expected_update_rate: 0.0
    }
