odom_frame: odom
base_link_frame: base_link
world_frame: odom

two_d_mode: true    # true <=> 0 at z, roll, pitch, vz, vroll, vpitch, az and fuses them
#dynamic_process_noise_covariance: true
frequency: 50

# configuration order -> [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
# non-holonomic robot -> output should have vy, ay = 0

odom0: odometry/gps
odom0_config: [true,  true,  false,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom0_queue_size: 10
odom0_nodelay: false
odom0_differential: true

odom1: odometry/vo
odom1_config: [true,  true,  false,
               false, false, true,
               false, false, false,
               false, false, false,
               false, false, false]
odom1_queue_size: 10
odom1_nodelay: false
odom1_differential: true

imu0: imu/data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              true,  false, false]
imu0_queue_size: 10
imu0_nodelay: false
imu0_differential: false
imu0_relative: true
imu0_remove_gravitational_acceleration: true
