odom_frame: odom
base_link_frame: base_link
world_frame: odom

two_d_mode: true                    #false | true <=> 0 stis times sxetikes me Z, roll, pitch
dynamic_process_noise_covariance: true
frequency: 50

odom0: odometry/gps                 # navsat_transform_node output | used for velocity verification : if almost 0, supports no movement, else have probably moved
odom0_config: [true,  true,  true,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom0_queue_size: 10
odom0_nodelay: false                # isos true vasi paradeigmatos
odom0_differential: true

odom1: /odom                        # camera, computed via rtabmap (visual_odometry.launch)
odom1_config: [true,  true,  true,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom1_queue_size: 10
odom1_nodelay: false
odom1_differential: true            # is true in order to find velocities from pose change | preferred this because twist is regarding rgbd_base_link

#https://answers.ros.org/question/269030/imu-convention-for-robot_localization/
#https://answers.ros.org/question/298415/imu-data-to-be-used-with-robot_localization/
imu0: imu/data
imu0_config: [false, false, false,
              true,  true,  true,
              false, false, false,
              true,  true,  true,
              true,  false, false]  # mallon to lathos itan sto y accel, afou den epitrepetai katheti kinisi apeutheias
imu0_queue_size: 10
imu0_nodelay: false
imu0_differential: false
#imu0_relative: true # gia na exoume roll pitch yaw se sxesi me arxiki katastasi??
imu0_remove_gravitational_acceleration: true
