global_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0 #1.0
    publish_frequency: 1.0 # for visualization, else 0.0
    static_map: true
    rolling_window: false

    plugins:
        - {name: static_layer,      type: "costmap_2d::StaticLayer"}
        - {name: obstacle_layer,    type: "costmap_2d::VoxelLayer"}
        - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}

    obstacle_layer:
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 20 # max_height / z_resolution -> z_voxels(20) * z_resolution(0.05) = 1 meter = max_obstacle_height defined at costmap_common_params
        publish_voxel_map: true # visualization at rviz

    inflation_layer:
        inflation_radius:     0.2  # max. distance from an obstacle at which costs are incurred for planning paths.
        cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
