kymco_maxxer90_joint_publisher:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

kymco_maxxer90_ackermann_steering_controller:
    type: "ackermann_steering_controller/AckermannSteeringController"
    rear_wheel: "RWD_joint"
    front_steer: "steering_wheel_joint"
    publish_rate: 50
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    cmd_vel_timeout: 0.5
    # wheel_separation_h : 0.4
    wheel_radius : 0.2286
    wheel_separation_h: 0.97
    wheel_separation_h_multiplier: 1.0
    steer_pos_multiplier: 1.0
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: false #true 
    # open_loop: true

    linear:
        x:
            has_velocity_limits    : true
            max_velocity           : 6.1  # m/s
            min_velocity           : 0.0 # m/s
            # has_acceleration_limits: true
            # max_acceleration       : 0.8  # m/s^2
            # min_acceleration       : 0.0 # m/s^2
            # has_jerk_limits        : true
            # max_jerk               : 5.0 # m/s^3

    angular:
        z:
            has_velocity_limits    : false
            # max_velocity           : 1.7  # rad/s
            # has_acceleration_limits: true
            # max_acceleration       : 1.5  # rad/s^2
            # has_jerk_limits        : true
            # max_jerk               : 2.5 # rad/s^3

gazebo_ros_control:
    pid_gains:
        front_left_steering_wheel_joint:
            p: 20.0
            i: 0.1
            d: 0.0
            i_clamp: 0.2
            antiwindup: false
            publish_state: true
        front_right_steering_wheel_joint:
            p: 20.0
            i: 0.1
            d: 0.0
            i_clamp: 0.2
            antiwindup: false
            publish_state: true
        RWD_joint:
            p: 200.0
            i: 0.1
            d: 0.0
        front_left_wheel:
            p: 200.0
            i: 0.1
            d: 0.0
        front_right_wheel:
            p: 200.0
            i: 0.1
            d: 0.0
        steering_wheel_joint:
            p: 200.0
            i: 0.1
            d: 0.0

