<?xml version="1.0"?>
<robot name="kymco_maxxer90" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find kymco_maxxer90_description)/urdf/wheel.urdf.xacro"/>
    <xacro:include filename="$(find kymco_maxxer90_description)/urdf/front_wheel.urdf.xacro"/>

    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="distance_from_ground" value="0.35"/> <!-- TODO -->
    <xacro:property name="wheelbase" value="0.970"/>
    <xacro:property name="wheel_diameter" value="0.4572"/>
    <xacro:property name="wheel_width" value="0.15"/>
    <xacro:property name="track" value="0.835"/>

    <!-- Chassis -->
    <link name="base_link" />

    <link name="chassis_link">
        <inertial>
            <mass value="68"/>
            <origin xyz="-0.25 0 ${distance_from_ground}" rpy="0 0 0"/>
            <inertia  ixx="6.997767154121414" ixy="0" ixz="0" iyy="17.876069102859596" iyz="0" izz="18.49883625698101" />
        </inertial>
        <visual>
            <origin xyz="0 0 ${distance_from_ground}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://kymco_maxxer90_description/meshes/chassis.stl" scale="1.0 1.0 1.0"/>
            </geometry>
            <material name="black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 ${distance_from_ground}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://kymco_maxxer90_description/meshes/chassis.stl" scale="1.0 1.0 1.0"/>
            </geometry>
        </collision>
    </link>

    <joint name="chassis_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />"
        <child link="chassis_link" />"
    </joint>


    <gazebo reference="chassis_link">
        <material>Gazebo/Black</material>
    </gazebo>"

    <!-- Steering wheel -->
    <link name="steering_wheel_link">
        <inertial>
            <mass value="5"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        </inertial>
    </link>

    <joint name="steering_wheel_joint" type="revolute">
        <origin xyz="-0.3 0 0.8" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="steering_wheel_link" />
        <axis xyz="0 0 1" />
        <limit lower="${-PI*25/180}" upper="${PI*25/180}" effort="100000" velocity="0.95"/>
        <dynamics damping="10" friction="0.3" />
    </joint>

    <transmission name="steering_wheel_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="steering_wheel_joint">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="steering_wheel_actuator">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <!-- Engine -->
    <link name="engine_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://kymco_maxxer90_description/meshes/engine.stl" scale="1.3 1.3 1.3"/>
            </geometry>
            <material name="silver">
                <color rgba="0.3 0.3 0.3 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://kymco_maxxer90_description/meshes/engine.stl" scale="1.3 1.3 1.3"/>
            </geometry>
        </collision>
    </link>

    <joint name="engine_joint" type="fixed">
        <origin xyz="-0.08 0 ${distance_from_ground+0.05}" rpy="0 0 0"/>
        <parent link="base_link" />
        <child link="engine_link" />
    </joint>

    <gazebo reference="engine_link">
        <material>Gazebo/Grey</material>
    </gazebo>"

    <!-- Wheels -->
    <xacro:kymco_maxxer90_front_wheel wheel_prefix="front_right">
        <origin xyz="0.33 ${track/2} ${distance_from_ground/2}" rpy="0 0 ${PI}"/>
    </xacro:kymco_maxxer90_front_wheel>

    <xacro:kymco_maxxer90_front_wheel wheel_prefix="front_left">
        <origin xyz="0.33 ${-track/2} ${distance_from_ground/2}" rpy="0 0 0"/>
    </xacro:kymco_maxxer90_front_wheel>

    <xacro:kymco_maxxer90_wheel wheel_prefix="rear_right">
        <origin xyz="0 ${track/2} 0" rpy="0 0 ${PI}"/>
    </xacro:kymco_maxxer90_wheel>

    <xacro:kymco_maxxer90_wheel wheel_prefix="rear_left">
        <origin xyz="0 ${-track/2} 0" rpy="0 0 0"/>
    </xacro:kymco_maxxer90_wheel>


    <link name="rear_suspension_link" >
        <inertial>
            <mass value="10"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
        </inertial>
    </link>

    <joint name="rear_suspension_joint" type="prismatic">
        <origin xyz="${0.33-wheelbase} 0 ${distance_from_ground/2}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="rear_suspension_link"/>
        <axis xyz="0 0 -1" />
        <limit lower="-0.1" upper="0.1" effort="500" velocity="10"/>
        <!-- <dynamics damping="1" friction="0.2"/> -->
    </joint>

    <gazebo reference="rear_suspension_joint">
        <provideFeedback>true</provideFeedback>
        <implicitSpringDamper>true</implicitSpringDamper>
        <springStiffness>30000</springStiffness>
        <springReference>0</springReference>
    </gazebo>

    <transmission name="rear_suspension_trans" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="rear_suspension_actuator">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        <joint name="rear_suspension_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
    </transmission>

    <link name="rear_axle_link">
        <visual>
            <origin xyz="0 0.05 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://kymco_maxxer90_description/meshes/differential.stl" scale="1.6 1.6 1.6"/>
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <origin xyz="0 0.05 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://kymco_maxxer90_description/meshes/differential.stl" scale="1.6 1.6 1.6"/>
            </geometry>
        </collision>
    </link>

    <joint name="rear_axle_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="rear_suspension_link" />
        <child link="rear_axle_link" />
    </joint>

    <gazebo reference="rear_axle_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <link name="RWD">
        <inertial>
            <mass value="10"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
        </inertial>
    </link>

    <joint name="RWD_joint" type="continuous">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="rear_suspension_link" />
        <child link="RWD" />
        <axis xyz="0 1 0" />
    </joint>

    <transmission name="non_differential_trans" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="non_differential_motor">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        <joint name="RWD_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
    </transmission>

    <link name="front_plate_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.3 0.4 0.01"/>
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.3 0.4 0.01"/>
            </geometry>
        </collision>
    </link>

    <joint name="front_plate_joint" type="fixed">
        <origin xyz="0.33 0 0.65" rpy="0 0 0"/>
        <parent link="base_link" />
        <child link="front_plate_link" />
    </joint>

    <gazebo reference="front_plate_link">
        <material>Gazebo/Grey</material>
    </gazebo>"

    <link name="rear_plate_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.3 0.4 0.01"/>
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.3 0.4 0.01"/>
            </geometry>
        </collision>
    </link>

    <joint name="rear_plate_joint" type="fixed">
        <origin xyz="-0.75 0 0.67" rpy="0 ${PI/13} 0"/>
        <parent link="base_link" />
        <child link="rear_plate_link" />
    </joint>

    <gazebo reference="rear_plate_link">
        <material>Gazebo/Grey</material>
    </gazebo>"

    <link name="rear_trans_chassis_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.22 0.02"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.22 0.02"/>
            </geometry>
        </collision>
    </link>

    <joint name="rear_trans_chassis_joint" type="fixed">
        <origin xyz="-0.57 0 0.48" rpy="0 0 0"/>
        <parent link="base_link" />
        <child link="rear_trans_chassis_link" />
    </joint>

    <gazebo reference="rear_trans_chassis_link">
        <material>Gazebo/Black</material>
    </gazebo>"

    <link name="rear_trans_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.02" length="0.28"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.02" length="0.28"/>
            </geometry>
        </collision>
    </link>

    <joint name="rear_trans_joint" type="fixed">
        <origin xyz="-0.6 0 0.34" rpy="0 ${PI/16} 0"/>
        <parent link="base_link" />
        <child link="rear_trans_link" />
    </joint>

    <gazebo reference="rear_trans_link">
        <material>Gazebo/Black</material>
    </gazebo>"

    <link name="rear_trans_spring_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://kymco_maxxer90_description/meshes/spring.stl" scale="1.0 1.0 1.0"/>
            </geometry>
            <material name="red">
                <color rgba="0.8 0 0 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://kymco_maxxer90_description/meshes/spring.stl" scale="1.0 1.0 1.0"/>
            </geometry>
        </collision>
    </link>

    <gazebo reference="rear_trans_spring_link">
        <material>Gazebo/Red</material>
    </gazebo>"

    <joint name="rear_trans_spring_joint" type="fixed">
        <origin xyz="-0.6 0 0.34" rpy="0 ${PI/16} 0"/>
        <parent link="base_link" />
        <child link="rear_trans_spring_link" />
    </joint>

    <link name="front_right_trans_chassis_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.3 0.02 0.01"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.3 0.02 0.01"/>
            </geometry>
        </collision>
    </link>

    <joint name="front_right_trans_chassis_joint" type="fixed">
        <origin xyz="0.33 0.16 0.4" rpy="0 0 0"/>
        <parent link="base_link" />
        <child link="front_right_trans_chassis_link" />
    </joint>

    <gazebo reference="front_right_trans_chassis_link">
        <material>Gazebo/Black</material>
    </gazebo>"

    <link name="front_right_trans_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.02" length="0.28"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.02" length="0.28"/>
            </geometry>
        </collision>
    </link>

    <joint name="front_right_trans_joint" type="fixed">
        <origin xyz="0.33 0.25 0.29" rpy="${PI/5} ${-PI/10} 0"/>
        <parent link="base_link" />
        <child link="front_right_trans_link" />
    </joint>

    <gazebo reference="front_right_trans_link">
        <material>Gazebo/Black</material>
    </gazebo>"

    <link name="front_right_trans_spring_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://kymco_maxxer90_description/meshes/spring.stl" scale="1.0 1.0 1.0"/>
            </geometry>
            <material name="red">
                <color rgba="0.8 0 0 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://kymco_maxxer90_description/meshes/spring.stl" scale="1.0 1.0 1.0"/>
            </geometry>
        </collision>
    </link>

    <joint name="front_right_trans_spring_joint" type="fixed">
        <origin xyz="0.33 0.25 0.29" rpy="${PI/5} ${-PI/10} 0"/>
        <parent link="base_link" />
        <child link="front_right_trans_spring_link" />
    </joint>

    <gazebo reference="front_right_trans_spring_link">
        <material>Gazebo/Red</material>
    </gazebo>"

    <link name="front_left_trans_chassis_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.3 0.02 0.01"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.3 0.02 0.01"/>
            </geometry>
        </collision>
    </link>

    <joint name="front_left_trans_chassis_joint" type="fixed">
        <origin xyz="0.33 -0.16 0.4" rpy="0 0 0"/>
        <parent link="base_link" />
        <child link="front_left_trans_chassis_link" />
    </joint>

    <gazebo reference="front_left_trans_chassis_link">
        <material>Gazebo/Black</material>
    </gazebo>"

    <link name="front_left_trans_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.02" length="0.28"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.02" length="0.28"/>
            </geometry>
        </collision>
    </link>

    <joint name="front_left_trans_joint" type="fixed">
        <origin xyz="0.33 -0.25 0.29" rpy="${-PI/5} ${-PI/10} 0"/>
        <parent link="base_link" />
        <child link="front_left_trans_link" />
    </joint>

    <gazebo reference="front_left_trans_link">
        <material>Gazebo/Black</material>
    </gazebo>"

    <link name="front_left_trans_spring_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://kymco_maxxer90_description/meshes/spring.stl" scale="1.0 1.0 1.0"/>
            </geometry>
            <material name="red">
                <color rgba="0.8 0 0 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://kymco_maxxer90_description/meshes/spring.stl" scale="1.0 1.0 1.0"/>
            </geometry>
        </collision>
    </link>

    <joint name="front_left_trans_spring_joint" type="fixed">
        <origin xyz="0.33 -0.25 0.29" rpy="${-PI/5} ${-PI/10} 0"/>
        <parent link="base_link" />
        <child link="front_left_trans_spring_link" />
    </joint>

    <gazebo reference="front_left_trans_spring_link">
        <material>Gazebo/Red</material>
    </gazebo>"

    <!-- Sensors -->
    <link name="gps_link"/>

    <joint name="gps_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link" />
        <child link="gps_link" />
    </joint>

    <link name="imu_link"/>

    <joint name="imu_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint>

    <link name="camera_link"/>

    <joint name="camera_joint" type="fixed">
        <origin xyz="0.5 0.0 0.4" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="camera_link"/>
    </joint>

    <link name="rgbd_optical_camera_frame"/>

    <joint name="rgbd_optical_camera_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="camera_link"/>
        <child link="rgbd_optical_camera_frame"/>
    </joint>

    <link name="rgbd_depth_camera_frame"/>

    <joint name="rgbd_depth_camera_joint" type="fixed">
        <origin xyz="0.0 0 0" rpy="${-PI/2} 0 ${-PI/2}"/>
        <parent link="rgbd_optical_camera_frame"/>
        <child link="rgbd_depth_camera_frame"/>
    </joint>

    <gazebo reference="rgbd_optical_camera_frame">
        <sensor type="depth" name="camera">
            <always_on>true</always_on>
            <update_rate>30.0</update_rate>
            <camera>
                <horizontal_fov>${110.0*PI/180.0}</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>720</width>
                    <height>540</height>
                </image>
                <clip>
                    <near>0.2</near>
                    <far>10.0</far>
                </clip>
            </camera>
            <plugin name="camera_plugin" filename="libgazebo_ros_openni_kinect.so">
                <baseline>0.2</baseline>
                <alwaysOn>true</alwaysOn>
                <!-- <cameraName>camera_ir</cameraName> -->
                <imageTopicName>/camera/color/image_raw</imageTopicName>
                <cameraInfoTopicName>/camera/color/camera_info</cameraInfoTopicName>
                <depthImageTopicName>/camera/depth/image_raw</depthImageTopicName>
                <depthImageCameraInfoTopicName>/camera/depth/camera_info</depthImageCameraInfoTopicName>
                <pointCloudTopicName>/camera/depth/points</pointCloudTopicName>
                <frameName>rgbd_depth_camera_frame</frameName>
                <pointCloudCutoff>0.2</pointCloudCutoff>
                <pointCloudCutoffMax>10.0</pointCloudCutoffMax>
                <distortionK1>-0.16</distortionK1>
                <distortionK2>0.01</distortionK2>
                <distortionK3>-0.02</distortionK3>
                <distortionT1>0.004</distortionT1>
                <distortionT2>-0.01</distortionT2>
                <CxPrime>0</CxPrime>
                <Cx>0</Cx>
                <Cy>0</Cy>
                <focalLength>0</focalLength>
                <hackBaseline>0</hackBaseline>
            </plugin>
        </sensor>
    </gazebo>


    <!-- Gazebo plugins -->
    <gazebo>
        <plugin name="gps_sensor" filename="libhector_gazebo_ros_gps.so">
            <robotNamespace>/</robotNamespace>
            <updateRate>40</updateRate>
            <bodyName>base_link</bodyName>
            <frameId>gps_link</frameId>
            <topicName>navsat/fix</topicName>
            <velocityTopicName>navsat/vel</velocityTopicName>
            <referenceLatitude>37.9949</referenceLatitude>
            <referenceLongitude>23.819173</referenceLongitude>
            <referenceHeading>0</referenceHeading>
            <referenceAltitude>0</referenceAltitude>
            <drift>0.0001 0.0001 0.0001</drift>
        </plugin>
        <plugin name="imu_sensor" filename="libhector_gazebo_ros_imu.so">
            <updateRate>50.0</updateRate>
            <bodyName>base_link</bodyName>
            <frameId>base_link</frameId>
            <topicName>imu/data</topicName>
            <accelDrift>0.00001 0.00001 0.00001</accelDrift>
            <accelGaussianNoise>0.001 0.001 0.001</accelGaussianNoise>
            <rateDrift>0.001 0.001 0.001</rateDrift>
            <rateGaussianNoise>0.01 0.01 0.01</rateGaussianNoise>
        </plugin>
        <plugin name="ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace></robotNamespace>
            <robotParam>robot_description</robotParam>
            <controlPeriod>0.001</controlPeriod>
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
            <legacyModeNS>true</legacyModeNS>               <!-- Probably needed to work at ROS Kinetic, ignore otherwise -->
        </plugin>

        <!-- Groundtruth perfect odometry plugin for evaluation purposes -->
        <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>50.0</updateRate>
            <bodyName>base_link</bodyName>
            <topicName>odom_perfect</topicName>
            <gaussianNoise>0.01</gaussianNoise>
            <frameName>world</frameName>
        </plugin>
    </gazebo>

</robot>
